### ISSUE TITLE
Seg Fault in Windows

### ISSUE THREAD

**Issue by regaw-leinad** [poliva/nbimg#1]
Still when running on windows (your exe download and compiled directly from your source) this seg faults (see below for details) on converting 720x1280 bmps to nbs.  More specifically I figured out that it is not the resolution but the file size of the bmp.  In the convertBMP2NB() method (and I found it to be the same in convertNB2BMP()) your unsigned long dataLen param doesn't always allow the full value of the file size to be stored. If you want to look at the changes I made that fix that (changed to a long long and a few other fixes)  check out the pastebin here - http://pastebin.com/WSq82Sxp (these were the changes I made to your 1.1 version, and I labeled it 2.0, didn't know you were still actively supporting the project)

(gdb) run -F hq.bmp
Starting program: E:\sourceCode\C\nbimg/nbimg.exe -F hq.bmp
[New Thread 4668.0x150c]
=== nbimg v1.2
=== Convert IMG/NB <--> BMP splash screens
=== (c)2007-2012 Pau Oliva - pof @ xda-developers

[] File: hq.bmp
[] No padding added. Check file size.

Program received signal SIGSEGV, Segmentation fault.
0x00404863 in __chkstk_ms ()
(gdb) info stack
#0  0x00404863 in __chkstk_ms ()
#1  0x00401600 in convertBMP2NB (input=0x75e32960,

```
filename=0x28fab0 "hq.bmp", dataLen=2764854, addhtcsig=1, smartphone=0,
padsize=0, pattern=255) at nbimg.c:105
```
#2  0x004028c5 in main (argc=3, argv=0x592f48) at nbimg.c:527

(gdb)

**Comment by poliva** [comment]
Thanks for the pull request, i merged your changes in v1.2.1 :)
closing this issue now.
